# Generated by Django 3.0 on 2019-12-07 05:46

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='events/')),
                ('event_website', models.URLField()),
                ('date', models.DateTimeField()),
                ('description', tinymce.models.HTMLField()),
            ],
        ),
    ]
